---
- name: Gather System Facts
  ansible.builtin.setup:
    gather_subset:
      - system
  when: not hostvars['localhost'].ansible_facts
  delegate_to: localhost
  delegate_facts: True

- name: Load New Relic Shared Vars
  ansible.builtin.include_vars: ../../vars/all.yml
  when: newrelic_infra_collection_cli_version is not defined

- name: Install The New Relic CLI Tool
  delegate_to: localhost
  delegate_facts: True
  become: True
  vars:
    _arch: >-
      {{ (hostvars['localhost'].ansible_architecture == 'aarch64') | ternary('arm64', 'x86_64') }}
    _file_type: >-
      {{ (hostvars['localhost'].ansible_os_family == 'Debian') | ternary('deb', 'rpm') }}
    _url: "https://github.com/newrelic/newrelic-cli/releases/download/\
           v{{ newrelic_infra_collection_cli_version }}/newrelic-cli_{{ newrelic_infra_collection_cli_version }}_Linux_\
           {{ _arch }}.{{ _file_type }}"
  block:
    - name: Install CLI Tool From Deb
      ansible.builtin.apt:
        deb: "{{ _url }}"
        state: present
      run_once: True
      environment:
        DEBIAN_FRONTEND: noninteractive
      when: _file_type == 'deb'
    - name: Install CLI Tool From RPM
      ansible.builtin.dnf:
        name: "{{ _url }}"
        state: present
      run_once: True
      when: _file_type == 'rpm'
