---
- name: Check Required Variables
  ansible.builtin.assert:
    that:
      - integration_mssql_username is defined
      - integration_mssql_password is defined
    fail_msg: This is a required variable for this role
    quiet: True

- name: Check Instance or Port Is Defined
  ansible.builtin.fail:
    msg: One and only one of integration_mssql_instance and integration_mssql_port must be set
  when: >-
    (integration_mssql_instance is defined and integration_mssql_port is defined) or
    (integration_mssql_instance is not defined and integration_mssql_port is not defined)

- name: Obfuscate Authentication Parameters
  when: integration_mssql_obfuscate_secrets
  block:
    - name: Install New Relic CLI Locally
      ansible.builtin.include_tasks: "{{ role_path }}/../../playbooks/tasks/local_install_newrelic_cli.yml"
    - name: Obfuscate Username and Password
      ansible.builtin.set_fact:
        _integration_mssql_obfuscated_secrets:
          username: "{{ lookup('newrelic.infra.obfuscate_string', integration_mssql_username, seed=inventory_hostname) }}"
          password: "{{ lookup('newrelic.infra.obfuscate_string', integration_mssql_password, seed=inventory_hostname) }}"

- name: Set Instance Pretty Name
  ansible.builtin.set_fact:
    _integration_mssql_pretty_name: >-
      nr-mssql-{{ integration_mssql_hostname | replace('.', '_') }}-{{ (integration_mssql_port is defined) |
      ternary(integration_mssql_port, integration_mssql_instance) }}

- name: Install Agent
  block:
    - name: Check For Master MSSQL Config File
      ansible.windows.win_stat:
        path: "{{ integration_mssql_vars.root_dir }}\\{{ integration_mssql_vars.config_file }}"
      register: _check_file
    - name: Install SQL Server Integration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/Win32NT/install.yml"
      when: not _check_file.stat.exists
    - name: Remove Installer if present
      ansible.windows.win_file:
        path: 'c:\nrsqlserver.msi'
        state: absent

- name: Configure SQL Server Integration
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/Win32NT/config.yml"
